/**
 * Route matrix + `canAccessRoute` / `getPostLoginPath` in a module with **no** dependency on `navConfig`.
 * `lib/navConsistency.ts` imports from here so `lib/permissions.ts` can safely re-export nav helpers without circular ESM init.
 */

import { FEATURES } from '@/lib/featureFlags';

/** Matches Prisma schema enum Role — use this type to avoid depending on Prisma client export. */
export type Role =
  | 'EMPLOYEE'
  | 'MANAGER'
  | 'ASSISTANT_MANAGER'
  | 'ADMIN'
  | 'AREA_MANAGER'
  | 'SUPER_ADMIN'
  | 'DEMO_VIEWER';

/**
 * Route access matrix for `canAccessRoute` / `RouteGuard`: which path prefixes each role may open.
 *
 * **Relationship to nav:** `lib/navConfig.ts` drives the **sidebar** (labels, grouping, visibility).
 * Development checks: `lib/navConsistency.ts` warns if a nav item lists a role that `ROLE_ROUTES` denies.
 *
 * When adding routes: update both this matrix and `lib/navConfig.ts` so sidebar and deep links stay aligned.
 */
export const ROLE_ROUTES: Record<Role, string[]> = {
  EMPLOYEE: [
    '/nav',
    '/dashboard',
    '/employee',
    '/schedule/view',
    '/tasks',
    '/me/target',
    '/sales/my',
    '/sales/returns',
    '/leaves/requests',
    '/inventory/daily',
    '/inventory/zones',
    '/about',
    '/change-password',
  ],
  MANAGER: [
    '/nav',
    '/',
    '/dashboard',
    '/executive',
    '/executive/monthly',
    '/executive/insights',
    '/executive/compare',
    '/executive/employees',
    '/performance',
    '/approvals',
    '/schedule',
    '/schedule/view',
    '/schedule/edit',
    '/schedule/audit',
    '/schedule/audit-edits',
    '/tasks',
    '/tasks/monitor',
    '/tasks/setup',
    '/planner-export',
    '/sync/planner',
    '/leaves',
    '/boutique/leaves',
    '/boutique/tasks',
    '/inventory/daily',
    '/inventory/daily/history',
    '/inventory/zones',
    '/inventory/follow-up',
    '/admin/employees',
    '/admin/targets',
    '/targets',
    '/admin/sales-edit-requests',
    '/admin/control-panel/delegation',
    '/admin/import/sales',
    '/sales/daily',
    '/reports/weekly',
    '/sales/summary',
    '/sales/analytics',
    '/sales/returns',
    '/sales/import',
    '/sales/import-matrix',
    '/sales/import-issues',
    '/sales/monthly-matrix',
    '/sales/leadership-impact',
    '/kpi/upload',
    '/me/target',
    '/compliance',
    '/about',
    '/change-password',
  ],
  /** مساعد المدير: نفس صلاحيات الموظف + تعديل الجدول الأسبوعي + المصفوفة الشهرية */
  ASSISTANT_MANAGER: [
    '/nav',
    '/dashboard',
    '/employee',
    '/schedule/view',
    '/schedule/edit',
    '/schedule/editor',
    '/tasks',
    '/me/target',
    '/leaves/requests',
    '/inventory/daily',
    '/inventory/zones',
    '/sales/summary',
    '/sales/analytics',
    '/sales/returns',
    '/admin/import/sales',
    '/sales/import',
    '/sales/import-issues',
    '/sales/monthly-matrix',
    '/targets',
    '/about',
    '/change-password',
  ],
  ADMIN: [
    '/nav',
    '/',
    '/dashboard',
    '/executive',
    '/executive/monthly',
    '/executive/insights',
    '/executive/compare',
    '/executive/employees',
    '/performance',
    '/approvals',
    '/schedule',
    '/schedule/view',
    '/schedule/edit',
    '/schedule/audit',
    '/schedule/audit-edits',
    '/tasks',
    '/tasks/monitor',
    '/tasks/setup',
    '/planner-export',
    '/sync/planner',
    '/leaves',
    '/boutique/leaves',
    '/boutique/tasks',
    '/inventory/daily',
    '/inventory/daily/history',
    '/inventory/zones',
    '/inventory/follow-up',
    '/admin/employees',
    '/admin/targets',
    '/admin/sales-edit-requests',
    '/admin/sales-integrity',
    '/admin/users',
    '/admin/reset-emp-id',
    '/admin/reset-password',
    '/admin/coverage-rules',
    '/admin/kpi-templates',
    '/admin/import',
    '/admin/import-center',
    '/admin/historical-import',
    '/admin/administration',
    '/admin/audit/login',
    '/admin/boutiques',
    '/admin/regions',
    '/admin/boutique-groups',
    '/admin/memberships',
    '/admin/integrations/planner',
    '/admin/integrations/planner/completions',
    '/admin/control-panel/delegation',
    '/admin/system',
    '/admin/system/version',
    '/admin/system-audit',
    '/targets',
    '/sales/daily',
    '/reports/weekly',
    '/sales/summary',
    '/sales/analytics',
    '/sales/returns',
    '/sales/import',
    '/sales/import-matrix',
    '/sales/import-issues',
    '/sales/monthly-matrix',
    '/admin/sales/monthly-matrix-secure-edit',
    '/sales/leadership-impact',
    '/kpi/upload',
    '/me/target',
    '/compliance',
    '/about',
    '/change-password',
  ],
  AREA_MANAGER: [
    '/nav',
    '/',
    '/dashboard',
    '/executive',
    '/executive/monthly',
    '/executive/insights',
    '/executive/compare',
    '/executive/employees',
    '/performance',
    '/approvals',
    '/schedule/view',
    '/sync/planner',
    '/leaves',
    '/boutique/leaves',
    '/tasks',
    '/area/employees',
    '/area/targets',
    '/targets',
    '/targets/boutiques',
    '/targets/employees',
    '/targets/import',
    '/admin/targets',
    '/admin/import/sales',
    '/admin/sales-edit-requests',
    '/admin/integrations/planner',
    '/sales/summary',
    '/sales/analytics',
    '/sales/daily',
    '/reports/weekly',
    '/sales/returns',
    '/sales/leadership-impact',
    '/me/target',
    '/compliance',
    '/about',
    '/change-password',
  ],
  DEMO_VIEWER: [
    '/nav',
    '/dashboard',
    '/executive',
    '/executive/monthly',
    '/executive/insights',
    '/executive/compare',
    '/executive/employees',
    '/schedule/view',
    '/kpi/upload',
    '/about',
    '/change-password',
  ],
  SUPER_ADMIN: [
    '/nav',
    '/',
    '/dashboard',
    '/company',
    '/executive',
    '/executive/monthly',
    '/executive/insights',
    '/executive/compare',
    '/executive/employees',
    '/performance',
    '/approvals',
    '/schedule',
    '/schedule/view',
    '/schedule/edit',
    '/schedule/audit',
    '/schedule/audit-edits',
    '/tasks',
    '/tasks/monitor',
    '/tasks/setup',
    '/planner-export',
    '/sync/planner',
    '/leaves',
    '/boutique/leaves',
    '/boutique/tasks',
    '/inventory/daily',
    '/inventory/daily/history',
    '/inventory/zones',
    '/inventory/follow-up',
    '/admin/employees',
    '/admin/targets',
    '/admin/sales-edit-requests',
    '/admin/sales-integrity',
    '/admin/users',
    '/admin/reset-emp-id',
    '/admin/reset-password',
    '/admin/coverage-rules',
    '/admin/kpi-templates',
    '/admin/import',
    '/admin/import-center',
    '/admin/historical-import',
    '/admin/administration',
    '/admin/audit/login',
    '/admin/boutiques',
    '/admin/regions',
    '/admin/boutique-groups',
    '/admin/memberships',
    '/admin/integrations/planner',
    '/admin/integrations/planner/completions',
    '/admin/control-panel/delegation',
    '/admin/system',
    '/admin/system/version',
    '/admin/system-audit',
    '/area/employees',
    '/area/targets',
    '/targets',
    '/sales/daily',
    '/reports/weekly',
    '/sales/summary',
    '/sales/analytics',
    '/sales/returns',
    '/sales/import',
    '/sales/import-matrix',
    '/sales/import-issues',
    '/sales/monthly-matrix',
    '/admin/sales/monthly-matrix-secure-edit',
    '/sales/leadership-impact',
    '/kpi/upload',
    '/me/target',
    '/compliance',
    '/about',
    '/change-password',
  ],
};

export function canAccessRoute(role: Role, pathname: string): boolean {
  const pathOnly = pathname.split('?')[0]?.split('#')[0] ?? pathname;
  const allowed = ROLE_ROUTES[role];
  if (!allowed) return false;
  const effective = FEATURES.EXECUTIVE ? allowed : allowed.filter((r) => !r.startsWith('/executive'));
  if (effective.includes(pathOnly)) return true;
  return effective.some((route) => pathOnly === route || pathOnly.startsWith(route + '/'));
}

/**
 * First destination after login (and safe fallback when user opens `/` without access).
 * Must stay aligned with `ROLE_ROUTES` — do not default everyone to `/` (management-only for some roles).
 */
export function getPostLoginPath(role: Role): string {
  if (role === 'EMPLOYEE') return '/employee';
  if (canAccessRoute(role, '/')) return '/';
  if (canAccessRoute(role, '/dashboard')) return '/dashboard';
  if (canAccessRoute(role, '/employee')) return '/employee';
  if (canAccessRoute(role, '/nav')) return '/nav';
  return '/dashboard';
}
